import { Geist, Geist_Mono } from "next/font/google";
import "../css/globals.css";
import "../css/bootstrap.min.css";
import "../css/aos.css";
import "../css/glightbox.min.css";
import "../css/swiper-bundle.min.css";
import "../css/css2.css";
import 'bootstrap-icons/font/bootstrap-icons.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MADEX TEAM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
